/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer */

#ifndef _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
#define _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_ERROR_UNKNOWN
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_ERROR_UNKNOWN 1L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_ERROR_SERVER_DIED
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_ERROR_SERVER_DIED 100L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK 200L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_UNKNOWN
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_UNKNOWN 1L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_VIDEO_TRACK_LAGGING
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_VIDEO_TRACK_LAGGING 700L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_BAD_INTERLEAVING
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_BAD_INTERLEAVING 800L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_NOT_SEEKABLE
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_NOT_SEEKABLE 801L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_METADATA_UPDATE
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_METADATA_UPDATE 802L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_FRAMERATE_VIDEO
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_FRAMERATE_VIDEO 900L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_FRAMERATE_AUDIO
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO_FRAMERATE_AUDIO 901L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_NOP
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_NOP 0L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_PREPARED
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_PREPARED 1L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_PLAYBACK_COMPLETE
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_PLAYBACK_COMPLETE 2L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_BUFFERING_UPDATE
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_BUFFERING_UPDATE 3L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_SEEK_COMPLETE
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_SEEK_COMPLETE 4L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_SET_VIDEO_SIZE
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_SET_VIDEO_SIZE 5L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_ERROR
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_ERROR 100L
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_MEDIA_INFO 200L
/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    _setVideoSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer__1setVideoSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    setDataSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_setDataSource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    prepare
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_prepare
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    _start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer__1start
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    _stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer__1stop
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    _pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer__1pause
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    getVideoWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_getVideoWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    getVideoHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_getVideoHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    isPlaying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_isPlaying
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    seekTo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_seekTo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    getCurrentPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_getCurrentPosition
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    getDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_getDuration
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    _release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer__1release
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    _reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer__1reset
  (JNIEnv *, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    native_suspend_resume
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_native_1suspend_1resume
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    setAudioStreamType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_setAudioStreamType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_native_1setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_native_1finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
