/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "libavformat/avformat.h"
/* Header for class com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils */

#ifndef _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils
#define _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils
 * Method:    native_av_setInputFile
 * Signature: (Ljava/lang/String;)Lcom/v2soft/spoiq/ffmpeg/core/FFMPEGAVFormatContext;
 */
JNIEXPORT jobject JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils_native_1av_1setInputFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils
 * Method:    native_av_setOutput
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils_native_1av_1setOutput
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils
 * Method:    native_av_print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils_native_1av_1print
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils
 * Method:    native_av_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGUtils_native_1av_1release
  (JNIEnv *, jobject);

jobject AVFormatContext_create(JNIEnv *env, AVFormatContext *fileContext);

#ifdef __cplusplus
}
#endif
#endif
