/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_IFFMpegPlayer */

#ifndef _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_IFFMpegPlayer
#define _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGPlayer_IFFMpegPlayer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
