/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFrame */

#ifndef _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFrame
#define _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFrame
 * Method:    nativeRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFrame_nativeRelease
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
