/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFormatContext */

#ifndef _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFormatContext
#define _Included_com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFormatContext
#ifdef __cplusplus
extern "C" {
#endif
#undef com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFormatContext_AV_TIME_BASE
#define com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFormatContext_AV_TIME_BASE 1000000LL
/*
 * Class:     com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFormatContext
 * Method:    nativeRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_v2soft_spoiq_ffmpeg_core_FFMPEGAVFormatContext_nativeRelease
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
