/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_ffmpeg_FFMpegAVRational */

#ifndef _Included_com_media_ffmpeg_FFMpegAVRational
#define _Included_com_media_ffmpeg_FFMpegAVRational
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_media_ffmpeg_FFMpegAVRational
 * Method:    nativeRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpegAVRational_nativeRelease
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
