/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_ffmpeg_FFMpeg */

#ifndef _Included_com_media_ffmpeg_FFMpeg
#define _Included_com_media_ffmpeg_FFMpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_avcodec_register_all
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1avcodec_1register_1all
  (JNIEnv *, jobject);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_register_all
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1register_1all
  (JNIEnv *, jobject);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setInputFile
 * Signature: (Ljava/lang/String;)Lcom/media/ffmpeg/FFMpegAVFormatContext;
 */
JNIEXPORT jobject JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setInputFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setOutputFile
 * Signature: (Ljava/lang/String;)Lcom/media/ffmpeg/FFMpegAVFormatContext;
 */
JNIEXPORT jobject JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setOutputFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setBitrate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setBitrate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_newVideoStream
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1newVideoStream
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setAudioRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setAudioRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setAudioChannels
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setAudioChannels
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setVideoChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setVideoChannel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setFrameRate
 * Signature: (I)Lcom/media/ffmpeg/FFMpegAVRational;
 */
JNIEXPORT jobject JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setFrameRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setFrameAspectRatio
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setFrameAspectRatio
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setVideoCodec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setVideoCodec
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_setFrameSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1setFrameSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_parse_options
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1parse_1options
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_convert
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1convert
  (JNIEnv *, jobject);

/*
 * Class:     com_media_ffmpeg_FFMpeg
 * Method:    native_av_release
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_media_ffmpeg_FFMpeg_native_1av_1release
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
