/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_ffmpeg_FFMpegAVCodecContext */

#ifndef _Included_com_media_ffmpeg_FFMpegAVCodecContext
#define _Included_com_media_ffmpeg_FFMpegAVCodecContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_media_ffmpeg_FFMpegAVCodecContext
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpegAVCodecContext_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
