/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_ffmpeg_FFMpegAVFormatContext */

#ifndef _Included_com_media_ffmpeg_FFMpegAVFormatContext
#define _Included_com_media_ffmpeg_FFMpegAVFormatContext
#ifdef __cplusplus
extern "C" {
#endif
#undef com_media_ffmpeg_FFMpegAVFormatContext_AV_TIME_BASE
#define com_media_ffmpeg_FFMpegAVFormatContext_AV_TIME_BASE 1000000i64
/*
 * Class:     com_media_ffmpeg_FFMpegAVFormatContext
 * Method:    nativeRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpegAVFormatContext_nativeRelease
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
