/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_ffmpeg_FFMpegUtils */

#ifndef _Included_com_media_ffmpeg_FFMpegUtils
#define _Included_com_media_ffmpeg_FFMpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_media_ffmpeg_FFMpegUtils
 * Method:    native_av_setInputFile
 * Signature: (Ljava/lang/String;)Lcom/media/ffmpeg/FFMpegAVFormatContext;
 */
JNIEXPORT jobject JNICALL Java_com_media_ffmpeg_FFMpegUtils_native_1av_1setInputFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_media_ffmpeg_FFMpegUtils
 * Method:    native_av_setOutput
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpegUtils_native_1av_1setOutput
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_media_ffmpeg_FFMpegUtils
 * Method:    native_av_print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpegUtils_native_1av_1print
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_media_ffmpeg_FFMpegUtils
 * Method:    native_av_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_media_ffmpeg_FFMpegUtils_native_1av_1release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
