/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_ffmpeg_FFMpegAVOutputFormat */

#ifndef _Included_com_media_ffmpeg_FFMpegAVOutputFormat
#define _Included_com_media_ffmpeg_FFMpegAVOutputFormat
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
