/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_ffmpeg_FFMpegAVCodecTag */

#ifndef _Included_com_media_ffmpeg_FFMpegAVCodecTag
#define _Included_com_media_ffmpeg_FFMpegAVCodecTag
#ifdef __cplusplus
extern "C" {
#endif
#undef com_media_ffmpeg_FFMpegAVCodecTag_AVCODEC_MAX_AUDIO_FRAME_SIZE
#define com_media_ffmpeg_FFMpegAVCodecTag_AVCODEC_MAX_AUDIO_FRAME_SIZE 192000L
#ifdef __cplusplus
}
#endif
#endif
